### ISSUE TITLE
[FEAT] 백엔드 exception handler 설정

### ISSUE THREAD

**Issue by EunjiShin** [Techeer-TeamB/Telivery_BE#15]
## 📌 개요

- API response를 통일하기 위해 global exception handler를 구현합니다. 

<br>

## 🔍 기능 설명

- 성공했을 때의 response format
  ```
  // 객체 그대로 리턴
  {
	  "id" : 1,
	  "name" : "은지" 
  }
  ```
- 실패했을 때의 response format
  ```
  // 404 NOT FOUND 
  {
	  "code" : -101,
	  "message" : "DB에 데이터가 없습니다"
  }
  
  ```
<br>

## ❗ 연관 기능

모든 백엔드 API를 위 format에 맞춰 개발합니다. 

<br>

### ✅ 참고 사항

참고 레퍼런스, 스크린샷 등 issue와 관련된 참고 자료가 있다면 첨부해주세요.

**Comment by EunjiShin** [comment]
@HyunTaek5 
현택님~ 기본 세팅해주신 거 보면 exception이 아예 다른 패키지로 분리되어 있는데, 
그럼 excepton handling은 도메인별로가 아니라 한 파일로 관리하는 건가요?! 
multi module 설정 의도가 궁금합니다!

**Comment by HyunTaek5** [comment]
@EunjiShin 
원래 exception들을 하나의 패키지로 묶어서 exception 안에서 도메인별로 분류하려 했습니다 :)
한 개의 파일만 존재하던 이유는 그냥 코드 예시로 넣어놓은 거 였습니다! ㅋㅋㅋ 제가 자세히 설명을 해드렸어야 됬는데 ㅠㅠ
은지님이 슬랙에서 제안해주신 대로 도메인별 디렉토리 안에 exception 파일을 위치하는 것도 좋은 거 같습니다 :D
